=== sumit290785/jsfgenerator/jsfgenerator/resource/view.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Enums -->

	<xs:simpleType name="tagtreeid">
    	<xs:restriction base="xs:string">
        	<xs:enumeration value="entitypage" />
	        <xs:enumeration value="simpleform" />
	        <xs:enumeration value="complexform" />
	        <xs:enumeration value="listpage" />
	    </xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="placeholdername">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FORM" />
			<xs:enumeration value="INPUT" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="attributetypename">
		<xs:restriction base="xs:string">
			<xs:enumeration value="template" />
			<xs:enumeration value="xmlnamespace" />
			<xs:enumeration value="static" />
			<xs:enumeration value="expression" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Definition of tags -->
	
	<xs:complexType name="proxytagtype">
		<xs:attribute name="type" type="placeholdername" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="statictagtype">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="statictag" type="statictagtype"  />
			<xs:element name="proxytag" type="proxytagtype" />
			<xs:element name="attribute" type="attributetype" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="attributebasetype"  abstract="true">
		<xs:attribute name="key" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="attributetype">
		<xs:complexContent>
			<xs:extension base="attributebasetype">
				<xs:attribute name="value" type="xs:string" use="required"/>
				<xs:attribute name="type" type="attributetypename" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="expressionattributetype" abstract="true">
		<xs:complexContent>
			<xs:extension base="attributebasetype">
				<xs:attribute name="type" type="xs:string" use="required" fixed="expression"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="simpleformattributetype">
		<xs:complexContent>
			<xs:extension base="expressionattributetype">
				<xs:attribute name="value" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
        					<xs:enumeration value="SAVE" />
        					<xs:enumeration value="DELETE" />
        					<xs:enumeration value="REFRESH" />
	  					</xs:restriction>
	  				</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="complexformattributetype">
		<xs:complexContent>
			<xs:extension base="expressionattributetype">
				<xs:attribute name="value" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
        					<xs:enumeration value="ADD" />
        					<xs:enumeration value="REMOVE" />
	  					</xs:restriction>
	  				</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="inputtagattributetype">
		<xs:complexContent>
			<xs:extension base="expressionattributetype">
				<xs:attribute name="value" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
        					<xs:enumeration value="ENTITY_FIELD" />
	  					</xs:restriction>
	  				</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- Definition of tag trees -->
	
	<xs:complexType name="tagtreetype">
		<xs:sequence>
			<xs:element name="statictag" type="statictagtype" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="tagtreeid" use="required"/>
	</xs:complexType>
	
	<!-- Definition of input tags -->
	
	<xs:complexType name="inptutagtype">
		<xs:sequence>
			<xs:element name="statictag" type="statictagtype" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- root -->
	
	<xs:element name="view">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tagtree" type="tagtreetype" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="inputtag" type="inptutagtype" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== sumit290785/jsfgenerator/trunk/jsfgenerator/resource/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="view.xsd">
	<tagtree id="entitypage">
		<statictag name="ui:composition">
			<attribute type="template" value="layout/template.xhtml" />
		</statictag>
	</tagtree>
	
	<tagtree id="simpleform">
		<statictag name=""></statictag>
	</tagtree>
	
	<tagtree id="complexform">
		<statictag name=""></statictag>
	</tagtree>
	
</view>

=== sumit290785/jsfgenerator/trunk/jsfgenerator/resource/tagtrees.xml
<?xml version="1.0" encoding="UTF-8"?>
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="view.xsd">
	<tagtree id="entitypage">
		<statictag name="ui:composition">
			<statictag name="h:inputText">
				<attribute type="static" key="value" value="akarmi" />
			</statictag>
			<proxytag type="FORM" />
			
			<attribute type="xmlnamespace" value="h:http://java.sun.com/jsf/html" />
			<attribute type="xmlnamespace" value="ui:http://java.sun.com/jsf/facelets" />
			<attribute type="template" value="template.xhtml" />
		</statictag>
	</tagtree>
	
	<tagtree id="simpleform">
		<statictag name="table">
			<proxytag type="INPUT" />
		</statictag>
	</tagtree>
	
	<inputtag id="jsfgenerator.entitymodel.fields.TextFieldType">
		<statictag name="h:inputText">
			<attribute type="static" key="value" value="EXPRESSION"/>
		</statictag>
		
		<statictag name="h:inputTextArea">
			<attribute type="expression" key="value" value="EXPRESSION"/>
			<attribute type="static" key="cols" value="10"/>
		</statictag>
	
	</inputtag>
	
	<inputtag id="jsfgenerator.entitymodel.fields.NumberFieldType">
		<statictag name="h:inputText">
			<attribute type="expression" key="value" value="EXPRESSION"/>
		</statictag>
	</inputtag>
	
</view>
